name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-0 libgconf-2-4
        npm install

    - name: Run Playwright tests
      env:
        MY_APP_URL: http://localhost:3000
      run: |
        xvfb-run npm run test