name: Run Playwright and Generate LightHouse PDF Report

on:
  push:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          npm ci
          npx playwright install chromium
          npm install -g playwright lighthouse chrome-launcher axe-core chromium wait-on

      - name: Start the X server
        run: |
          export DISPLAY=:0
          startx & sleep 5

      - name: Start the application
        run: |
          export DISPLAY=:1
          npm run start & npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js

      - name: Generate Lighthouse Report and Convert it to PDF using create_pdf_from_lighthouseJsonOutput.js
        run: |
          lighthouse http://localhost:3000 --output json --output-path ./test-results/report.json --chrome-flags="--headless --no-sandbox --disable-gpu"
          npm install playwright
          node create_pdf_from_lighthouseJsonOutput.js
      - name: Upload report, screenshots and videos of failed tests
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
